#!/bin/bash
if nmcli radio  wifi | grep -q 'disabled'
then
  nmcli radio wifi on
fi
if iwgetid -r| grep -q 'PPM NHL'
then
  echo "Already connected to 'PPM NHL'"
else
  nmcli con up id 'PPM NHL'
fi
if nmcli con show --active| grep -q 'lio-internal'
then
  echo "Already connected to 'lio-internal'"
else
  nmcli con up id 'lio-internal'
fi
export ROS_MASTER_URI=http://192.168.100.110:11311
IP_VAR=$(hostname -I | awk '{print $3}')
export ROS_IP="$IP_VAR"

CURRENT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
echo 'Sourcing ' "$CURRENT_DIR/activate_catkin_ws"
source "$CURRENT_DIR/activate_catkin_ws"
