#!/bin/bash
if nmcli radio  wifi | grep -q 'disabled'
then
  nmcli radio wifi on
fi
if iwgetid -r| grep -q 'PPM NHL'
then
  echo "Already connected to 'PPM NHL'"
else
  nmcli con up id 'PPM NHL'
fi
if nmcli con show --active| grep -q 'lio-internal'
then
  nmcli con down id 'lio-internal'
fi
export ROS_MASTER_URI=
#IP_VAR=$(hostname -I | awk '{print $3}')
IP_VAR=
export ROS_IP="$IP_VAR"

#CURRENT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
#echo 'Sourcing ' "$CURRENT_DIR/activate_catkin_ws"
#source "$CURRENT_DIR/activate_catkin_ws"
